name: root_tissue_segmentation
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - _libgcc_mutex=0.1=conda_forge
    - _openmp_mutex=4.5=1_gnu
    - ca-certificates=2020.12.5=ha878542_0
    - certifi=2020.12.5=py39hf3d152e_1
    - ld_impl_linux-64=2.35.1=hea4e1c9_2
    - libffi=3.3=h58526e2_2
    - libgcc-ng=9.3.0=h2828fa1_19
    - libgomp=9.3.0=h2828fa1_19
    - libstdcxx-ng=9.3.0=h6de172a_19
    - ncurses=6.2=h58526e2_4
    - openssl=1.1.1k=h7f98852_0
    - pip=21.1.1=pyhd8ed1ab_0
    - python=3.9.4=hffdb5ce_0_cpython
    - python_abi=3.9=1_cp39
    - readline=8.1=h46c0cb4_0
    - sqlite=3.35.5=h74cdb3f_0
    - tk=8.6.10=h21135ba_1
    - tzdata=2021a=he74cb21_0
    - wheel=0.36.2=pyhd3deb0d_0
    - xz=5.2.5=h516909a_1
    - zlib=1.2.11=h516909a_1010
    -   pip:
            - absl-py==0.12.0
            - adabelief-pytorch==0.2.1
            - aiohttp==3.7.4.post0
            - albumentations==0.5.2
            - alembic==1.4.1
            - async-timeout==3.0.1
            - attrs==21.2.0
            - cachetools==4.2.2
            - chardet==4.0.0
            - click==8.0.0
            - cliff==3.7.0
            - cloudpickle==1.6.0
            - cmaes==0.8.2
            - cmd2==1.5.0
            - colorama==0.4.4
            - colorlog==5.0.1
            - commonmark==0.9.1
            - cupy==9.0.0
            - cycler==0.10.0
            - databricks-cli==0.14.3
            - decorator==4.4.2
            - docker==5.0.0
            - entrypoints==0.3
            - fastrlock==0.6
            - flask==2.0.0
            - fsspec==2021.5.0
            - future==0.18.2
            - gitdb==4.0.7
            - gitpython==3.1.17
            - google-auth==1.30.0
            - google-auth-oauthlib==0.4.4
            - greenlet==1.1.0
            - grpcio==1.37.1
            - gunicorn==20.1.0
            - idna==2.10
            - imageio==2.9.0
            - imgaug==0.4.0
            - itsdangerous==2.0.1
            - jinja2==3.0.1
            - joblib==1.0.1
            - json2html==1.3.0
            - kiwisolver==1.3.1
            - mako==1.1.4
            - markdown==3.3.4
            - markupsafe==2.0.1
            - matplotlib==3.4.2
            - mlflow==1.19.0
            - mpi4py==3.0.3
            - multidict==5.1.0
            - networkx==2.5.1
            - ninja==1.10.0.post2
            - nose==1.3.7
            - numpy==1.20.3
            - oauthlib==3.1.0
            - opencv-python==4.5.2.52
            - opencv-python-headless==4.5.2.52
            - optuna==2.8.0
            - packaging==20.9
            - pandas==1.2.4
            - pbr==5.6.0
            - pillow==8.2.0
            - pint==0.16.1
            - plotly==4.14.3
            - portalocker==2.3.0
            - prettytable==2.1.0
            - prometheus-client==0.10.1
            - prometheus-flask-exporter==0.18.2
            - protobuf==3.17.0
            - psutil==5.8.0
            - py-cpuinfo==7.0.0
            - pyasn1==0.4.8
            - pyasn1-modules==0.2.8
            - pydeprecate==0.3.0
            - pygments==2.9.0
            - pyparsing==2.4.7
            - pyperclip==1.8.2
            - python-dateutil==2.8.1
            - python-editor==1.0.4
            - pytorch-lightning==1.3.8
            - pytorch-toolbelt==0.4.3
            - pytz==2021.1
            - pyudev==0.22.0
            - pywavelets==1.1.1
            - pyyaml==5.4.1
            - querystring-parser==1.2.4
            - requests==2.25.1
            - requests-oauthlib==1.3.0
            - retrying==1.3.3
            - rich==10.2.1
            - rsa==4.7.2
            - ruamel-yaml==0.16.12
            - scikit-image==0.18.1
            - scikit-learn==0.24.2
            - scipy==1.6.3
            - setuptools==56.2.0
            - shapely==1.7.1
            - six==1.16.0
            - sklearn==0.0
            - smmap==4.0.0
            - sqlalchemy==1.4.15
            - sqlparse==0.4.1
            - stevedore==3.3.0
            - system-intelligence==2.0.2
            - tabulate==0.8.9
            - tensorboard==2.4.1
            - tensorboard-data-server==0.6.1
            - tensorboard-plugin-wit==1.8.0
            - tensorboardx==2.2
            - threadpoolctl==2.1.0
            - tifffile==2021.4.8
            - torch==1.8.0
            - torch-encoding==1.2.1
            - torch-optimizer==0.1.0
            - torchmetrics==0.3.2
            - torchvision==0.9.0
            - tqdm==4.60.0
            - typing-extensions==3.10.0.0
            - urllib3==1.26.4
            - wcwidth==0.2.5
            - websocket-client==1.0.0
            - werkzeug==2.0.1
            - wrapt==1.12.1
            - yarl==1.6.3
            - tifffile==2021.4.8
            - requests==2.25.1
prefix: /home/ubuntu/miniconda3/envs/root-tissue-segmentation
